-- T17 baseline schema is unchanged in T20.
-- Copy the committed T17 migrations into this directory before deployment.
-- This placeholder prevents T20 from silently replacing the repo's source of truth.
