-- Astro-Zodiac T17 — PostgreSQL baseline schema
-- Do not drop/replace the legacy SQLite database.py in T17.
-- IDs are generated by the application so the migration needs no extension.

BEGIN;

CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL DEFAULT '',
    role TEXT NOT NULL DEFAULT 'user',
    status TEXT NOT NULL DEFAULT 'active',
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    last_login_at TIMESTAMPTZ NULL
);

CREATE TABLE IF NOT EXISTS user_profiles (
    user_id UUID PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
    locale TEXT NOT NULL DEFAULT 'th-TH',
    timezone TEXT NOT NULL DEFAULT 'Asia/Bangkok',
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS membership_grants (
    membership_id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    product_id TEXT NOT NULL,
    status TEXT NOT NULL,
    source TEXT NOT NULL,
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NULL,
    external_reference TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, external_reference)
);
CREATE INDEX IF NOT EXISTS ix_membership_user_status ON membership_grants(user_id, status);
CREATE INDEX IF NOT EXISTS ix_membership_product ON membership_grants(product_id);

CREATE TABLE IF NOT EXISTS orders (
    order_id TEXT PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    product_id TEXT NOT NULL,
    amount_minor BIGINT NOT NULL CHECK (amount_minor >= 0),
    currency CHAR(3) NOT NULL,
    status TEXT NOT NULL,
    provider TEXT NULL,
    provider_payment_id TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    paid_at TIMESTAMPTZ NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS ix_orders_user_created ON orders(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_orders_provider_payment ON orders(provider, provider_payment_id);

CREATE TABLE IF NOT EXISTS payments (
    payment_id TEXT PRIMARY KEY,
    order_id TEXT NOT NULL REFERENCES orders(order_id) ON DELETE RESTRICT,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    provider TEXT NOT NULL,
    provider_payment_id TEXT NOT NULL,
    amount_minor BIGINT NOT NULL CHECK (amount_minor >= 0),
    currency CHAR(3) NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE(provider, provider_payment_id)
);
CREATE INDEX IF NOT EXISTS ix_payments_order ON payments(order_id);

CREATE TABLE IF NOT EXISTS webhook_events (
    event_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    event_type TEXT NOT NULL,
    provider_payment_id TEXT NULL,
    status TEXT NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ NULL,
    error_code TEXT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY(provider, event_id)
);
CREATE INDEX IF NOT EXISTS ix_webhook_payment ON webhook_events(provider, provider_payment_id);

CREATE TABLE IF NOT EXISTS charts (
    chart_id UUID PRIMARY KEY,
    user_id UUID NULL REFERENCES users(user_id) ON DELETE SET NULL,
    chart_hash TEXT NOT NULL,
    calculation_version TEXT NOT NULL,
    astrology_settings_version TEXT NOT NULL,
    ephemeris_version TEXT NULL,
    birth_data JSONB NOT NULL,
    normalized_chart JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE(chart_hash, calculation_version, astrology_settings_version)
);
CREATE INDEX IF NOT EXISTS ix_charts_user_created ON charts(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS analyses (
    analysis_id UUID PRIMARY KEY,
    chart_id UUID NOT NULL REFERENCES charts(chart_id) ON DELETE RESTRICT,
    analysis_type TEXT NOT NULL,
    pattern_engine_version TEXT NULL,
    evidence_engine_version TEXT NULL,
    validation_engine_version TEXT NULL,
    report_version TEXT NULL,
    result JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_analyses_chart_created ON analyses(chart_id, created_at DESC);

CREATE TABLE IF NOT EXISTS validation_sessions (
    validation_session_id UUID PRIMARY KEY,
    analysis_id UUID NOT NULL REFERENCES analyses(analysis_id) ON DELETE RESTRICT,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    pattern_id TEXT NOT NULL,
    status TEXT NOT NULL,
    component_scores JSONB NOT NULL DEFAULT '{}'::jsonb,
    result JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NULL
);
CREATE INDEX IF NOT EXISTS ix_validation_user_pattern ON validation_sessions(user_id, pattern_id, created_at DESC);

CREATE TABLE IF NOT EXISTS action_plans (
    plan_id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    pattern_id TEXT NOT NULL,
    intervention_id TEXT NULL,
    goal JSONB NOT NULL,
    plan JSONB NOT NULL,
    status TEXT NOT NULL,
    starts_at DATE NOT NULL,
    ends_at DATE NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_action_plans_user_status ON action_plans(user_id, status);

CREATE TABLE IF NOT EXISTS daily_checkins (
    checkin_id TEXT PRIMARY KEY,
    plan_id UUID NOT NULL REFERENCES action_plans(plan_id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    day_number INTEGER NOT NULL CHECK (day_number BETWEEN 1 AND 30),
    status TEXT NOT NULL,
    difficulty INTEGER NOT NULL CHECK (difficulty BETWEEN 1 AND 10),
    confidence INTEGER NOT NULL CHECK (confidence BETWEEN 1 AND 10),
    outcome INTEGER NULL CHECK (outcome BETWEEN 1 AND 10),
    reflection TEXT NULL,
    failure_reason TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE(plan_id, day_number)
);
CREATE INDEX IF NOT EXISTS ix_checkins_user_created ON daily_checkins(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS weekly_reviews (
    review_id TEXT PRIMARY KEY,
    plan_id UUID NOT NULL REFERENCES action_plans(plan_id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    period_start_day INTEGER NOT NULL,
    period_end_day INTEGER NOT NULL,
    result JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS plan_adjustments (
    adjustment_id TEXT PRIMARY KEY,
    plan_id UUID NOT NULL REFERENCES action_plans(plan_id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    day_number INTEGER NOT NULL,
    adjustment_type TEXT NOT NULL,
    reason TEXT NOT NULL,
    target_step_id TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS ai_usage_events (
    usage_event_id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    product_id TEXT NOT NULL,
    usage_type TEXT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    success BOOLEAN NOT NULL,
    request_id TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_ai_usage_user_created ON ai_usage_events(user_id, created_at DESC);

COMMIT;
